use crate::intern::Symbol;
use crate::span::Span;
use crate::stmt::Block;

#[derive(Debug, Clone)]
pub struct Expr {
    pub kind: ExprKind,
    pub span: Span,
}

impl Expr {
    pub fn new(kind: ExprKind, span: Span) -> Self {
        Self { kind, span }
    }
}

// AST equality is structural over `kind`; spans are metadata and would
// otherwise force tests to thread exact source positions through every
// expected-tree literal.
impl PartialEq for Expr {
    fn eq(&self, other: &Self) -> bool {
        self.kind == other.kind
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum ExprKind {
    Int(i64),
    Float(f64),
    Bool(bool),
    Str(String),
    Var(Symbol),
    /// The implicit receiver `this` inside a method body.
    This,
    /// `super.method(args)` — call the parent class's version of
    /// `method` directly (no virtual dispatch). `method = None`
    /// means `super(args)`, the parent's `init`, valid only inside
    /// a child class's own `init` body.
    SuperCall {
        method: Option<Symbol>,
        args: Box<[Expr]>,
    },
    Unary {
        op: UnOp,
        expr: Box<Expr>,
    },
    Binary {
        op: BinOp,
        lhs: Box<Expr>,
        rhs: Box<Expr>,
    },
    /// Short-circuit logical operator (`&&`, `||`). Separated from `Binary`
    /// so the evaluator can avoid evaluating the rhs when not needed.
    Logical {
        op: LogicalOp,
        lhs: Box<Expr>,
        rhs: Box<Expr>,
    },
    /// Free function call: `foo(args)`. Method calls go through MethodCall.
    Call {
        callee: Symbol,
        args: Box<[Expr]>,
    },
    /// `obj.field` — field read.
    Field {
        obj: Box<Expr>,
        name: Symbol,
    },
    /// `obj.method(args)`.
    MethodCall {
        obj: Box<Expr>,
        method: Symbol,
        args: Box<[Expr]>,
    },
    /// `new ClassName(args)` or `new ClassName<T, U>(args)` for
    /// generic instantiations. `type_args` is empty for non-generic
    /// classes. `init_method` is set by the post-typecheck mangler
    /// when the class has overloaded `init`s — it names the specific
    /// init that runtime should dispatch to. `None` means "look up
    /// `init` by name as before" (the common, non-overloaded case).
    New {
        class: Symbol,
        type_args: Box<[crate::Type]>,
        args: Box<[Expr]>,
        init_method: Option<Symbol>,
    },
    Block(Block),
    If {
        cond: Box<Expr>,
        then_branch: Block,
        /// `None`, another `If` (for `else if`), or a `Block`.
        else_branch: Option<Box<Expr>>,
    },
    While {
        cond: Box<Expr>,
        body: Block,
    },
    /// `for x in iter { body }` — iterates over an array, binding each
    /// element to `var` for the body. Always evaluates to `Unit`. The
    /// iter slot also accepts `Range` (`a..b` / `a..=b`) — see
    /// `ExprKind::Range`.
    ForIn {
        var: Symbol,
        iter: Box<Expr>,
        body: Block,
    },
    /// Integer range. `start` is required for any usable range
    /// expression (the for-in loop has no implicit lower bound);
    /// `end` may be `None` to express a `start..` (RangeFrom-style)
    /// open-ended iterator that must be exited by `break`.
    /// Inclusive form `start..=end` is only meaningful when `end`
    /// is `Some`.
    Range {
        start: Option<Box<Expr>>,
        end: Option<Box<Expr>>,
        inclusive: bool,
    },
    /// Construct a closure value. Generated by the JIT's hoist pass
    /// in place of an FnExpr; carries the hoisted wrapper fn name
    /// plus the (capture name, capture type) list. The JIT lowering
    /// allocates a closure struct, writes the wrapper's address,
    /// then writes each capture's value at successive 8-byte slots.
    /// The interpreter never produces or consumes this node.
    Closure {
        fn_name: Symbol,
        captures: Box<[(Symbol, crate::Type)]>,
    },
    /// Infinite loop. Exits only via `break` (or returning from the
    /// enclosing function once `return` exists). The expression's type
    /// is the type of the `break` value (or `Unit` for bare `break`).
    Loop {
        body: Block,
    },
    /// Exit the innermost enclosing `loop`/`while`. With an optional
    /// value (`break v`) the value becomes the result of the enclosing
    /// `loop`. `break v` is only valid inside `loop` (not `while`/`for`).
    /// Type checker rejects occurrences outside any loop.
    Break(Option<Box<Expr>>),
    /// Skip to the next iteration of the innermost enclosing loop.
    Continue,
    /// `await expr` — only legal inside an `async fn`. The
    /// inner must be `Promise<T>`; the await expression
    /// evaluates to `T` once the promise settles. Currently
    /// desugared to `.then(fn(v) { rest_of_body })`; a real
    /// state-machine transform is the eventual replacement.
    Await(Box<Expr>),
    /// `return` (with or without a value) — early exit from the
    /// enclosing function/method. Type checker rejects occurrences
    /// outside any function body.
    Return(Option<Box<Expr>>),
    /// Assignment to an existing variable. Always evaluates to `Unit`.
    Assign {
        target: Symbol,
        value: Box<Expr>,
    },
    /// Assignment to a field: `obj.field = value`. Evaluates to `Unit`.
    AssignField {
        obj: Box<Expr>,
        field: Symbol,
        value: Box<Expr>,
        /// `true` for synthetic loader-emitted writes that
        /// initialise a `const` static field whose declared
        /// initializer wasn't compile-time constant. The type
        /// checker exempts these from the
        /// "cannot assign to const static field" rule. Always
        /// `false` for parser-built assignments.
        is_init: bool,
    },
    /// Numeric (or `bool`-to-int) cast: `expr as Type`.
    Cast {
        expr: Box<Expr>,
        ty: crate::types::Type,
    },
    /// Runtime type test: `expr is Type` — returns `bool`. Walks the
    /// dynamic class's parent chain in RTTI, mirroring the behaviour
    /// of `typeof(expr)` lookups.
    TypeTest {
        expr: Box<Expr>,
        ty: crate::types::Type,
    },
    /// Runtime safe downcast: `expr as? Type` — returns `Type?`,
    /// `some(expr)` if the dynamic type is a subtype of `Type`,
    /// `none` otherwise.
    TypeDowncast {
        expr: Box<Expr>,
        ty: crate::types::Type,
    },
    /// Anonymous function expression — `fn(p: T): R { body }`. No
    /// captures (closures); at runtime it's a code pointer with the
    /// statically-known `Type::Fn` signature.
    FnExpr {
        params: Box<[crate::Param]>,
        ret: Option<crate::types::Type>,
        body: crate::stmt::Block,
    },
    /// Array literal: `[a, b, c]`.
    Array(Box<[Expr]>),
    /// Tuple literal `(a, b, ...)` — always 2+ elements (`(x)` is
    /// grouping). Heterogeneous; indexed via `t[N]` with a constant
    /// integer literal.
    Tuple(Box<[Expr]>),
    /// `Foo { f1: v1, f2: v2 }` — aggregate literal for an
    /// `@extern(C) struct`. The post-typecheck mangling pass desugars
    /// this into `new Foo()` plus a sequence of field assignments,
    /// so downstream stages (interpreter / JIT) never see this
    /// node directly.
    StructLit {
        class: Symbol,
        fields: Box<[(Symbol, Expr)]>,
        /// Source span of each entry's field name, parallel to
        /// `fields`. The AST itself doesn't need them, but LSP
        /// hover / go-to-def on a field name inside the literal
        /// (`cbSize:` inside `WNDCLASSEXA { cbSize: 80, ... }`)
        /// has nothing to anchor on otherwise. Construction sites
        /// outside the parser usually clone these verbatim from
        /// the source literal; passes that synthesise fields
        /// from scratch can fill with `Span::dummy()`.
        field_name_spans: Box<[Span]>,
    },
    /// Map literal: `{ "a": 1, "b": 2 }`. Keys must be K-typed
    /// expressions (string / int / bool literals at parse time;
    /// validated against the inferred K by the type checker).
    MapLit(Box<[(Expr, Expr)]>),
    /// Index read: `obj[idx]`.
    Index {
        obj: Box<Expr>,
        index: Box<Expr>,
    },
    /// Index write: `obj[idx] = value`.
    AssignIndex {
        obj: Box<Expr>,
        index: Box<Expr>,
        value: Box<Expr>,
    },
    /// `none` literal — its concrete `T?` type is determined by context.
    None,
    /// `some(x)` constructor: wraps `x` of type `T` as a `T?` value.
    Some(Box<Expr>),
    /// `if let some(name) = expr { then } else { ... }`. Inside `then`,
    /// `name` is bound to the unwrapped value of type `T` (where the
    /// scrutinee has type `T?`).
    IfLet {
        name: Symbol,
        expr: Box<Expr>,
        then_branch: Block,
        else_branch: Option<Box<Expr>>,
    },
    /// `EnumName::Variant` (Phase 1: unit) or `EnumName::Variant(args)` /
    /// `EnumName::Variant { f: v }` (Phase 2: payload).
    EnumCtor {
        enum_name: Symbol,
        variant: Symbol,
        args: CtorArgs,
    },
    /// `match scrutinee { Pattern => body, ... }`.
    Match {
        scrutinee: Box<Expr>,
        arms: Box<[MatchArm]>,
    },
}

#[derive(Debug, Clone, PartialEq)]
pub enum CtorArgs {
    Unit,
    Tuple(Box<[Expr]>),
    Struct(Box<[(Symbol, Expr)]>),
}

#[derive(Debug, Clone)]
pub struct MatchArm {
    pub pattern: Pattern,
    pub body: Expr,
    pub span: crate::span::Span,
}

impl PartialEq for MatchArm {
    fn eq(&self, other: &Self) -> bool {
        self.pattern == other.pattern && self.body == other.body
    }
}

#[derive(Debug, Clone)]
pub struct Pattern {
    pub kind: PatternKind,
    pub span: crate::span::Span,
}

impl PartialEq for Pattern {
    fn eq(&self, other: &Self) -> bool {
        self.kind == other.kind
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum PatternKind {
    /// `_` — matches anything, binds nothing.
    Wildcard,
    /// `EnumName::Variant` (Phase 1) or with bindings (Phase 2).
    /// `enum_name` is `None` when the user writes the short form
    /// (just `Variant(...)`); the type checker resolves it from the
    /// match scrutinee's static type.
    Variant {
        enum_name: Option<Symbol>,
        variant: Symbol,
        bindings: PatternBindings,
    },
    /// `42`, `-7` — integer literal pattern. The natural type is
    /// `i64`; the type checker coerces to the scrutinee's type when
    /// it's a same-signed narrower / wider integer.
    IntLit(i64),
    /// `1..5` (exclusive) or `1..=5` (inclusive) — integer range
    /// pattern for primitive `match`. `low <= x` and either
    /// `x < high` or `x <= high`.
    /// Integer range pattern. Either bound may be `None` to form
    /// a half-open pattern (`..N`, `..=N`, `N..`). The
    /// type-checker rejects empty / both-`None` shapes.
    IntRange { low: Option<i64>, high: Option<i64>, inclusive: bool },
    /// `true` / `false` — bool literal pattern.
    BoolLit(bool),
    /// `"hello"` — string literal pattern, structural equality.
    StrLit(String),
}

#[derive(Debug, Clone, PartialEq)]
pub enum PatternBindings {
    /// Unit variant (no inner pattern).
    Unit,
    /// `EnumName::Variant(name1, name2)` — positional bindings (`_`
    /// for "ignore"); the strings are the binding names.
    Tuple(Box<[Symbol]>),
    /// `EnumName::Variant { f1: name1, f2 }` (shorthand allowed).
    Struct(Box<[(Symbol, Symbol)]>),
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UnOp {
    Neg,
    Pos,
    Not,
    /// Bitwise NOT (`~`). Operand must be `i64`.
    BitNot,
    /// Address-of (`&local`). Only valid inside an `@extern(C)`
    /// context; the operand must be a local variable. Result type
    /// is `*T` where `T` is the local's declared type. Forces the
    /// local into a stack slot at codegen so the pointer is stable.
    AddrOf,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinOp {
    Add,
    Sub,
    Mul,
    Div,
    Rem,
    Eq,
    Ne,
    Lt,
    Le,
    Gt,
    Ge,
    /// Bitwise operators. All require `i64` on both sides and produce `i64`.
    BitAnd,
    BitOr,
    BitXor,
    Shl,
    Shr,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LogicalOp {
    And,
    Or,
}
