pub use ilang_ast::Span;

#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    Int(i64),
    Float(f64),
    Str(String),
    Ident(String),
    // keywords
    Let,
    Fn,
    If,
    Else,
    While,
    Loop,
    Break,
    Continue,
    Return,
    True,
    False,
    Class,
    New,
    This,
    As,
    None_,
    Some_,
    // punctuation
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    LParen,
    RParen,
    LBrace,
    RBrace,
    LBracket,
    RBracket,
    Semicolon,
    Comma,
    Colon,
    ColonColon,
    Equals,
    PlusEq,
    MinusEq,
    StarEq,
    SlashEq,
    PercentEq,
    EqEq,
    BangEq,
    Lt,
    LtEq,
    Gt,
    GtEq,
    AmpAmp,
    PipePipe,
    Amp,
    AmpEq,
    Pipe,
    PipeEq,
    Caret,
    CaretEq,
    Tilde,
    LtLt,
    LtLtEq,
    GtGt,
    GtGtEq,
    Bang,
    Dot,
    Hash,
    Question,
    Eof,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub span: Span,
    /// `true` if at least one newline appeared between the previous token
    /// (or start of input) and this token. Used by the parser for
    /// JS-style automatic semicolon insertion at statement boundaries.
    pub leading_newline: bool,
    /// Set on numeric literals that ended with a type suffix (`1_i32`,
    /// `1.5f32`, ...). The parser wraps such literals in an explicit
    /// `as`-cast so the rest of the pipeline sees the declared type.
    pub numeric_suffix: Option<ilang_ast::Type>,
}
