//! Emit `.il` files from the parsed GIR repo.

use std::collections::HashSet;
use std::fs;
use std::io::Write;
use std::path::Path;

use std::collections::HashMap;

use crate::types::{
    EnumDef, FunDef, Namespace, ParamDir, Repo, TypeRef, render_type,
};

const GENERATED_HEADER: &str =
    "// AUTO-GENERATED by `cargo run -p gtk4-bindgen`. DO NOT EDIT.\n\n";

pub fn emit(repo: &Repo, out_dir: &Path) -> Result<(), String> {
    if let Err(e) = fs::create_dir_all(out_dir) {
        return Err(format!("create_dir_all {}: {e}", out_dir.display()));
    }
    write_header_doc(out_dir)?;

    let known = crate::parse::known_type_set(repo);
    let c_types = crate::parse::c_type_map(repo);
    let mut emitted_files: Vec<String> = Vec::new();
    // Tracks every C type already emitted by an earlier namespace's
    // file so later namespaces skip the duplicate. GLib + GObject
    // both define `GIOCondition` (a GIR quirk), and Gdk + Gio share
    // `GAppLaunchContext` for compatibility.
    let mut global_emitted: HashSet<String> = HashSet::new();

    for ns in &repo.namespaces {
        let file_stem = format!("gen_{}", ns.name.to_lowercase());
        let path = out_dir.join(format!("{file_stem}.il"));
        let body = emit_namespace(ns, &known, &c_types, &mut global_emitted);
        fs::write(&path, body)
            .map_err(|e| format!("writing {}: {e}", path.display()))?;
        emitted_files.push(file_stem);
    }

    Ok(())
}

fn write_header_doc(out_dir: &Path) -> Result<(), String> {
    let path = out_dir.join("GENERATED.md");
    let body = "# generated GTK 4 bindings\n\n\
        The `gen_<ns>.il` files in this directory are emitted by \
        `gtk4-bindgen` from the GObject Introspection metadata \
        (`/opt/homebrew/share/gir-1.0/Gtk-4.0.gir` on macOS, the distro \
        equivalent on Linux). Do not hand-edit; rerun \
        `cargo run -p gtk4-bindgen -- --gir ... --out bindings/gtk4` \
        to refresh.\n";
    fs::write(&path, body)
        .map_err(|e| format!("writing {}: {e}", path.display()))
}

fn emit_namespace(
    ns: &Namespace,
    known: &HashSet<String>,
    c_types: &HashMap<String, String>,
    global_emitted: &mut HashSet<String>,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str(&format!(
        "/// {} namespace — {} classes, {} records, {} enums, {} functions \
         from `<{}>`. Constructors / methods / namespace-level functions \
         that reference unsupported parameter shapes (out, callbacks, arrays, \
         GError, …) are skipped on this pass.\n\n",
        ns.name,
        ns.classes.len(),
        ns.records.len(),
        ns.enums.len(),
        ns.classes
            .iter()
            .map(|c| c.constructors.len() + c.methods.len() + c.funcs.len())
            .sum::<usize>()
            + ns.funcs.len(),
        ns.name
    ));

    // ─── Enums ──────────────────────────────────────────────
    for en in &ns.enums {
        if en.deprecated {
            continue;
        }
        let key = if en.c_type.is_empty() { en.name.clone() } else { en.c_type.clone() };
        if !global_emitted.insert(format!("enum:{key}")) {
            continue;
        }
        emit_enum(&mut out, en);
    }

    // ─── `@extern(C, "gtk-4")` block: handles + functions ───
    out.push_str("@extern(C, \"gtk-4\") {\n");

    // Class & record handle structs — keyed off the C type to avoid
    // cross-namespace name collisions (`Gtk.AppLaunchContext` vs
    // `Gio.AppLaunchContext`).
    for c in &ns.classes {
        if c.deprecated || c.c_type.is_empty() {
            continue;
        }
        if global_emitted.insert(format!("struct:{}", c.c_type)) {
            out.push_str(&format!("    @handle pub struct {} {{}}\n", c.c_type));
        }
    }
    for r in &ns.records {
        if r.deprecated || r.c_type.is_empty() {
            continue;
        }
        if global_emitted.insert(format!("struct:{}", r.c_type)) {
            out.push_str(&format!("    @handle pub struct {} {{}}\n", r.c_type));
        }
    }
    out.push('\n');

    // Constructors / methods / class-funcs / ns-funcs.
    let mut skipped = 0usize;
    let mut local_emitted = 0usize;
    for c in &ns.classes {
        if c.deprecated {
            continue;
        }
        for f in &c.constructors {
            if try_emit_fn(&mut out, f, &ns.name, known, c_types, global_emitted) {
                local_emitted += 1;
            } else {
                skipped += 1;
            }
        }
        for f in &c.methods {
            if try_emit_fn(&mut out, f, &ns.name, known, c_types, global_emitted) {
                local_emitted += 1;
            } else {
                skipped += 1;
            }
        }
        for f in &c.funcs {
            if try_emit_fn(&mut out, f, &ns.name, known, c_types, global_emitted) {
                local_emitted += 1;
            } else {
                skipped += 1;
            }
        }
    }
    for f in &ns.funcs {
        if try_emit_fn(&mut out, f, &ns.name, known, c_types, global_emitted) {
            local_emitted += 1;
        } else {
            skipped += 1;
        }
    }

    out.push_str("}\n");
    out.push_str(&format!(
        "\n// {} fn(s) emitted, {} skipped (unsupported params/return or already exported by another namespace)\n",
        local_emitted, skipped
    ));
    out
}

fn emit_enum(out: &mut String, en: &EnumDef) {
    if en.members.is_empty() {
        return;
    }
    // Prefer the C type name (`GtkOrientation`) so cross-namespace
    // enums with the same GIR `name` don't collide.
    let surface = if en.c_type.is_empty() {
        en.name.clone()
    } else {
        en.c_type.clone()
    };
    if en.is_flags {
        out.push_str("@flags\n");
    }
    out.push_str(&format!("pub enum {}: u32 {{\n", surface));
    let mut seen_values: HashSet<i64> = HashSet::new();
    for m in &en.members {
        // ilang enums forbid duplicate values; drop aliases.
        if !seen_values.insert(m.value) {
            continue;
        }
        let v = m.value as u64;
        // Hex format for flag-like values; plain decimal for small
        // sequential enums.
        let value_str = if en.is_flags || v > 0xffff {
            format!("0x{v:x}")
        } else {
            v.to_string()
        };
        out.push_str(&format!("    {} = {value_str}\n", sanitize_member(&m.name)));
    }
    out.push_str("}\n\n");
}

fn sanitize_member(name: &str) -> String {
    // GIR member names are lowercase-with-hyphens. Convert to
    // lower_snake; replace leading-digit names with `key0` etc. so
    // they parse as identifiers.
    let mut s: String = name
        .chars()
        .map(|c| if c == '-' { '_' } else { c })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s = format!("v{}", s);
    }
    if is_ilang_keyword(&s) {
        s.push('_');
    }
    s
}

fn is_ilang_keyword(s: &str) -> bool {
    matches!(
        s,
        "fn" | "let" | "if" | "elif" | "else" | "while" | "for" | "in"
            | "loop" | "break" | "continue" | "return" | "match"
            | "class" | "init" | "deinit" | "pub" | "use" | "const"
            | "static" | "true" | "false" | "none" | "some" | "as"
            | "new" | "this" | "super" | "extends" | "enum" | "struct"
            | "union" | "type"
    )
}

fn try_emit_fn(
    out: &mut String,
    f: &FunDef,
    cur_ns: &str,
    known: &HashSet<String>,
    c_types: &HashMap<String, String>,
    global_emitted: &mut HashSet<String>,
) -> bool {
    if f.deprecated || f.variadic || f.throws || f.c_identifier.is_empty() {
        return false;
    }
    if !global_emitted.insert(format!("fn:{}", f.c_identifier)) {
        return false;
    }
    if !signature_supported(f, cur_ns, known) {
        return false;
    }

    let mut params_render = Vec::<String>::new();
    if let Some(inst) = &f.instance {
        params_render.push(format!("self: {}", render_type(inst, c_types)));
    }
    for p in &f.params {
        if p.direction != ParamDir::In {
            return false; // unreachable — supported check rejects these
        }
        let pname = if p.name.is_empty() || is_ilang_keyword(&p.name) {
            "arg".to_string()
        } else {
            p.name.clone()
        };
        params_render.push(format!("{}: {}", pname, render_type(&p.ty, c_types)));
    }
    let ret = match &f.return_type {
        Some(t) if !matches!(t, TypeRef::Unsupported(_)) => {
            format!(": {}", render_type(t, c_types))
        }
        _ => String::new(),
    };
    let plist = params_render.join(", ");
    out.push_str(&format!(
        "    @symbol(\"{}\") @lib pub fn {}({plist}){ret}\n",
        f.c_identifier, f.c_identifier
    ));
    true
}

fn signature_supported(
    f: &FunDef,
    cur_ns: &str,
    known: &HashSet<String>,
) -> bool {
    if let Some(t) = &f.instance {
        if !type_supported(t, cur_ns, known) {
            return false;
        }
    }
    for p in &f.params {
        if p.direction != ParamDir::In {
            return false;
        }
        if !type_supported(&p.ty, cur_ns, known) {
            return false;
        }
    }
    if let Some(t) = &f.return_type {
        if !type_supported(t, cur_ns, known) {
            return false;
        }
    }
    true
}

fn type_supported(t: &TypeRef, _cur_ns: &str, known: &HashSet<String>) -> bool {
    match t {
        TypeRef::Primitive(_) | TypeRef::String | TypeRef::VoidPtr => true,
        TypeRef::Named(qual) => known.contains(qual),
        TypeRef::Unsupported(_) => false,
    }
}

/// Rewrite the umbrella `gtk.il` so it re-exports only the
/// `generated/` subtree.
pub fn write_umbrella(
    umbrella_path: &Path,
    stems: &[String],
) -> Result<(), String> {
    let mut body = String::new();
    body.push_str(GENERATED_HEADER);
    body.push_str(
        "/// GTK 4 bindings — umbrella module.\n\
         ///\n\
         /// Re-exports every `gen_<ns>.il` file produced by \
         `gtk4-bindgen` (lives under `generated/`). Hand-written \
         bindings at the package root (`core.il`, `input.il`, \
         `menu.il`, `widgets.il`) are intentionally NOT re-exported \
         here — they sit on disk as a reference until they're either \
         ported back into the generator or deleted.\n\n",
    );
    for stem in stems {
        body.push_str(&format!("pub use generated.{stem}.*\n"));
    }
    fs::write(umbrella_path, body)
        .map_err(|e| format!("writing {}: {e}", umbrella_path.display()))
}

/// Convenience for the CLI driver.
pub fn discover_emitted_stems(out_dir: &Path) -> Vec<String> {
    let mut out = Vec::new();
    let Ok(entries) = fs::read_dir(out_dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let p = entry.path();
        if p.extension().and_then(|s| s.to_str()) != Some("il") {
            continue;
        }
        let stem = match p.file_stem().and_then(|s| s.to_str()) {
            Some(s) if s.starts_with("gen_") => s.to_string(),
            _ => continue,
        };
        out.push(stem);
    }
    out.sort();
    out
}

// keep the io::Write import alive for users that pull this module into
// a streamed-output context later
#[allow(dead_code)]
fn _io_write_kept(_w: &mut dyn Write) {}
